# These are supported funding model platforms

github: AorsiniYT # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: Aorsini # Replace with a single Patreon username
ko_fi: Aorsini # Replace with a single Ko-fi username
